// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMi6pfW7zUSfqvMv5qeWtLO6gOwhc6FxE',
    appId: '1:462064658462:web:056a1dd55fa72bd6fc260f',
    messagingSenderId: '462064658462',
    projectId: 'denovo-f24a4',
    authDomain: 'denovo-f24a4.firebaseapp.com',
    databaseURL: 'https://denovo-f24a4-default-rtdb.firebaseio.com',
    storageBucket: 'denovo-f24a4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnGmtFm1aCYbxUXEKfIhnaPe9_CvKB0aM',
    appId: '1:462064658462:android:157d9d4190ef4953fc260f',
    messagingSenderId: '462064658462',
    projectId: 'denovo-f24a4',
    databaseURL: 'https://denovo-f24a4-default-rtdb.firebaseio.com',
    storageBucket: 'denovo-f24a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhIZ6g1Q2ePKf_SOEdyQ4MA9WzYgDoZec',
    appId: '1:462064658462:ios:8d8754e26325251cfc260f',
    messagingSenderId: '462064658462',
    projectId: 'denovo-f24a4',
    databaseURL: 'https://denovo-f24a4-default-rtdb.firebaseio.com',
    storageBucket: 'denovo-f24a4.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhIZ6g1Q2ePKf_SOEdyQ4MA9WzYgDoZec',
    appId: '1:462064658462:ios:205face76a49e70afc260f',
    messagingSenderId: '462064658462',
    projectId: 'denovo-f24a4',
    databaseURL: 'https://denovo-f24a4-default-rtdb.firebaseio.com',
    storageBucket: 'denovo-f24a4.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
